<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="wrap about-wrap" id="enlighter-about">

    <!-- News Title !-->
    <h1>Welcome to Enlighter <?php echo ENLIGHTER_VERSION ?></h1>

    <!-- News Subtext !-->
    <div class="about-text">
        Thanks for upgrading! Many new features and improvements are available that you will enjoy.
    </div>

    <!-- Logo on the right !-->
    <div id="EnlighterBadge"></div>

    <!-- Settings Tabs -->
    <h2 class="nav-tab-wrapper" id="EnlighterTabNav">
        <a data-tab="EnlighterTabNews" class="nav-tab"><?php _e('What&#8217;s New', 'enlighter'); ?></a>
        <a data-tab="EnlighterTabChangelog" class="nav-tab"><?php _e('Changelog', 'enlighter'); ?></a>
    </h2>

    <!-- Latest News !-->
    <div id="EnlighterTabNews">
        <div class="headline">
            <h3 class="headline-title">Multisite/Network Support</h3>

            <div class="featured-image">
                <img
                    src="<?php echo Enlighter\ResourceManager::getResourceUrl('about/multisite.png'); ?>"
                    alt="Multisite Support">
            </div>

            <p class="introduction">Enlighter on your Network Site.</p>

            <p>All Features, including the Theme Customizer are now compatible with Network installations!</p>

        </div>

        <hr />

        <div class="column-layout-2">

            <div class="col-md-2">
                <div class="news-section">
                    <h4>Markdowwn in bbPress</h4>

                    <div class="news-image">
                        <img
                            src="<?php echo Enlighter\ResourceManager::getResourceUrl('about/bbpress_markdown.png'); ?>"
                            alt="Use Enlighter within bbPress posts.">
                    </div>

                    <p>Your bbPress community can use markdown style code-blocks to highlight source-code within forum posts. Goto <code>Enlighter -> Extensions</code> to enable it!</p>

                </div>

            </div>

            <div class="col-md-2">
                <div class="news-section">
                    <h4>Environment Checks</h4>

                    <div class="news-image">
                        <img
                            src="<?php echo Enlighter\ResourceManager::getResourceUrl('about/environment_check.png'); ?>"
                            alt="Environment Check">
                    </div>

                    <p>Some additional environment checks are added to verify that Enlighter can work on your site. The notices are only visible on the Enlighter Settings page for admin users.</p>

                </div>

            </div>

            <div class="clear"></div>

        </div>
    </div>

    <!-- Changelog Tab !-->
    <div id="EnlighterTabChangelog">
        <h3 class="changelog-title">What have been changed in <?php echo ENLIGHTER_VERSION ?></h3>

        <?php include(ENLIGHTER_PLUGIN_PATH.'/views/admin/Changes.html'); ?>

        <p class="changelog-more">Need more ? The view the <a href="https://github.com/AndiDittrich/WordPress.Enlighter/blob/master/CHANGES.md">full history on GitHub</a></p>

    </div>

    <hr />

    <!-- Footer NAV !-->
    <p class="related"><strong>Related:</strong>
        <a href="https://twitter.com/andidittrich/">@AndiDittrich</a> &bullet;
        <a href="https:/andidittrich.de">Author's Page</a> &bullet;
        <a href="http://enlighterjs.org">EnlighterJS</a>
    </p>
    <p class="related"><strong>GitHub:</strong>
        <a href="https://github.com/AndiDittrich/WordPress.Enlighter">Development</a> &bullet;
        <a href="https://github.com/AndiDittrich/WordPress.Enlighter/issues">Report Bugs</a> &bullet;
        <a href="https://github.com/AndiDittrich/WordPress.Enlighter/commits/master">Commits</a> &bullet;
        <a href="https://github.com/AndiDittrich/WordPress.Enlighter/blob/master/CHANGES.md">Changelog</a> &bullet;
        <a href="https://github.com/AndiDittrich/WordPress.Enlighter/releases">Releases</a>
    </p>

</div>