<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<hr />

<p class="credits">
    <a href="https://enlighterjs.org">Enlighter</a> <?php _e('is developed by', 'enlighter'); ?> <a href="https://andidittrich.com">Andi Dittrich</a>.
    <?php printf(__('It`s released under the terms of the %s', 'enlighter'), '<a href="#TB_inline?width=800&height=550&inlineId=enlighter-license" class="thickbox">'.__('GPL-2.0', 'enlighter').'</a>'); ?><br />
    <strong><?php _e('Includes:', 'enlighter'); ?></strong>
      <a href="https://github.com/EnlighterJS/EnlighterJS">EnlighterJS 3</a> - MPL 2.0 <?php _e('License', 'enlighter'); ?>
    | <a href="https://github.com/EnlighterJS/Plugin.TinyMCE">EnlighterJS TinyMCE Plugin</a> - MPL 2.0 <?php _e('License', 'enlighter'); ?>
    | <a href="https://github.com/EnlighterJS/Plugin.Gutenberg">EnlighterJS Gutenberg Editor Plugin</a> - MPL 2.0 <?php _e('License', 'enlighter'); ?>
    | <a href="https://github.com/EnlighterJS/Plugin.ThemeCustomizer">EnlighterJS Theme Customizer Plugin</a> - MPL 2.0 <?php _e('License', 'enlighter'); ?>
    | <a href="https://github.com/AndiDittrich/WP-Skeleton">WP-Skeleton</a> - MPL 2.0 <?php _e('License', 'enlighter'); ?>
</p>
<hr />
