<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Visual Editor -->
<div class="postbox">
	<h3 class="hndle"><span><?php _e('Visual Editor (TinyMCE 4)', 'enlighter'); ?></span></h3>
	<div class="inside EnlighterBlockcontent">

        <!-- TinyMCE Integration -->
        <h4><?php _e('Visual Editor Integration', 'enlighter'); ?></h4>
        <p><?php _e('Enlighter can directly integrated into the Visual-Editor by adding Preformatted styles for each supported language as well as additional buttons to the toolbar.', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displayCheckbox(__('Enable Backend Integration', 'enlighter'), 'enableTinyMceIntegration'); ?>

        <p><?php _e('Do you want to use the Visual Editor extensions in your frontend (website) ? May required for frontend editing plugins..', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displayCheckbox(__('Enable Frontend Integration', 'enlighter'), 'enableFrontendTinyMceIntegration'); ?>

        <!-- TinyMCE Tweaks -->
        <h4><?php _e('Visual Editor Tweaks', 'enlighter'); ?></h4>
        <p><?php _e('WordPress Limits the Editor-Width to ~600px. You can disable this limit - might be useful for posting source-code!', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displayCheckbox(__('Automatic Width (max)', 'enlighter'), 'editorAutowidth'); ?>


        <!-- Codeblock Font Styles -->
        <h4><?php _e('Code-Block Styles', 'enlighter'); ?></h4>
        <p><?php _e('It is also possible to influence the code-block styles of the Visual-Editor. Maybe you like another background color or font-family.', 'enlighter'); ?></p>


        <?php
        // font family
        $this->_settingsUtility->displayInput(__('Font-Family', 'enlighter'), 'editorFontFamily', __('e.g. "Source Code Pro", "Liberation Mono", "Courier New", Courier, monospace', 'enlighter'), '', true);

        // font size
        $this->_settingsUtility->displayInput(__('Font-Size', 'enlighter'), 'editorFontSize', __('e.g. 0.7em', 'enlighter'), '', true);

        // line height
        $this->_settingsUtility->displayInput(__('Line height', 'enlighter'), 'editorLineHeight', __('e.g. 1.4em', 'enlighter'), '', true);

        // font color
        $this->_settingsUtility->displayInput(__('Font-Color', 'enlighter'), 'editorFontColor', __('e.g. #565b60', 'enlighter'), 'EnlighterJSColorChooser', true);

        // background color
        $this->_settingsUtility->displayInput(__('Background-Color', 'enlighter'), 'editorBackgroundColor', __('e.g. #f7f7f7', 'enlighter'), 'EnlighterJSColorChooser', true);
        ?>

        <input type="button" value="<?php _e('Restore defaults', 'enlighter');?> " id="enlighter_editorstylesDefault" class="button button-primary" />

    </div>
</div>

<!-- Text Editor -->
<div class="postbox">
    <h3 class="hndle"><span><?php _e('Text/HTML Editor', 'enlighter'); ?></span></h3>
    <div class="inside EnlighterBlockcontent">

    </div>
</div>
