<?php
/**
	Descriptionn: Enlighter Error Page
	Plugin URI: http://andidittrich.de/go/enlighterjs
	Version: 2.0
	Author: Andi Dittrich
	Author URI: http://andidittrich.de
	License: MIT X11-License
	
	Copyright (c) 2013-2014, Andi Dittrich

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
?>
<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>
<!-- EnligherSettings:wrap -->
<div class="wrap" id="EnlighterSettings">

<!-- Main Title -->
<h2 class="maintitle"><?php _e('Enlighter - Customizable Syntax Highlighter', 'enlighter'); ?></h2>

<style type="text/css">
	#EnlighterEnvironmentError{
		width: 400px !important;
		height: 200px !important;
		margin: 5% auto 0% auto !important;
		padding: 10px;
		border: solid 1px #e5e5e5;
		box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.04);
		background-color: #ffffff;
	}
</style>

<!-- Error Message -->
<div id="EnlighterEnvironmentError">
	<h2><?php _e('Environment Error'); ?></h2>
	<ul> 
    	<?php 
    	// PHP version
   		echo '<li>Installed PHP Version: <strong style="color: #cc0a00">', phpversion() ,'</strong><br /> <strong>(PHP >= 5.3 is required to run this plugin)</strong></li>';
   		echo '<li>Please upgrade your PHP installation</li>';
    	?>
    </ul>	
</div>


</div>
<!-- // EnligherSettings:wrap -->
<div class="clear"></div>
