<?php
/**
	Descriptionn: Enlighter Error Page
	Plugin URI: http://www.a3non.org/go/enlighterjs
	Version: 1.7
	Author: Andi Dittrich
	Author URI: http://andidittrich.de
	License: MIT X11-License
	
	Copyright (c) 2013-2014, Andi Dittrich

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
?>
<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="wrap">
<h2><?php _e('Enlighter - Advanced javascript based syntax highlighting', 'enlighter'); ?></h2>

<!-- Breadcrumb -->
<div id='setting-error-settings_updated' class='updated settings-error'> 
<p><strong><?php _e('Enlighter related: ', 'enlighter'); ?></strong>
	<a href="https://github.com/AndiDittrich/EnlighterJS"><?php _e('EnlighterJS on GitHub', 'enlighter'); ?></a> | 
	<a href="http://wordpress.org/plugins/enlighter/"><?php _e('Enlighter on WordPress.org', 'enlighter'); ?></a> | 
	<a href="https://github.com/AndiDittrich/WordPress.Enlighter/issues"><?php _e('Report a Bug', 'enlighter'); ?></a> |
	<a href="http://static.andidittrich.de/EnlighterJS/Demo.html"><?php _e('Theme Demo', 'enlighter'); ?></a>
</p>
</div>

<!-- System Info -->
<h3><?php _e('Environment Error'); ?></h3>
<div id='setting-error-settings_updated' class='updated settings-error'> 
    <ul> 
    	<?php 
    	// PHP version
    	if (version_compare(phpversion(), '5.3', '>=')){
    		echo '<li>PHP Version: <strong style="color: #00cc00">', phpversion() , '</strong></li>';
    	}else{
    		echo '<li>PHP Version: <strong style="color: #cc0a00">', phpversion() ,'</strong> <strong>(PHP >= 5.3 is required to run this plugin)</strong></li>';
    		echo '<li>Please upgrade your PHP installation</li>';
    	}
    	?>
    </ul>	
</div>
</div>
