<div id="enlighter-license" style="display:none;">

<p><strong>Enlighter Plugin - Copyright (c) 2010-<?php echo date('Y'); ?></strong>
 <a href="https://andidittrich.de">Andi Dittrich &lt;https://andidittrich.de&gt;</a></p>

<hr />

<h3>GNU GENERAL PUBLIC LICENSE - Version 2, June 1991</h3>

<p>This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2
of the License.</p>

<p>This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.</p>

<p>You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.</p>
</div>