<?php
/**
	Descriptionn: Enlighter Admin Settings Page
	Plugin URI: http://www.a3non.org/go/enlighterjs
	Version: 1.0
	Author: Andi Dittrich
	Author URI: http://andidittrich.de
	License: MIT X11-License
	
	Copyright (c) 2013, Andi Dittrich

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
?>
<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="wrap">
<div id="icon-options-general" class="icon32"><br /></div>
<h2><?php _e('Enlighter - Advanced javascript based syntax highlighting'); ?></h2>

<!-- Breadcrumb -->
<?php add_thickbox(); ?>
<div id='setting-error-settings_updated' class='updated settings-error'> 
<p><strong>Enlighter related: </strong>
	<a href="#TB_inline?height=500&width=800&inlineId=EnlighterHelp" class="thickbox" rel="Enlighter Help">View Help</a> | 
	<a href="https://github.com/AndiDittrich/EnlighterJS">EnlighterJS on GitHub</a> | 
	<a href="http://wordpress.org/extend/plugins/enlighter">Enlighter on WordPress.org</a> | 
	<a href="https://github.com/AndiDittrich/WordPress.Enlighter/issues">Report a Bug</a> |
	<a href="http://static.andidittrich.de/EnlighterJS/Demo.html">Theme Demo</a>
</p>
</div>

<!-- Help Overlay Content -->
<?php require('Help.phtml'); ?>

<!-- settings !-->
<form method="post" action="options.php">
    <?php settings_fields('enlighter-settings-group' ); ?>
    
	<!-- appearance !-->
    <h2><?php _e('Appearance'); ?></h2>
    <p><?php _e('You can specify the default language and theme as well as the some output styles. If you want to customize themes, choose the default theme option "custom"');?><br />
    <?php _e('The indent-option will replace each tab at the beginning of a line with a selectable number of space-characters'); ?></p>

    <!-- Theme -->
	<?php $sUtil->displaySelect('Default Theme', 'defaultTheme', $themes); ?>
    
    <!-- Language -->
	<?php $sUtil->displaySelect('Default Language', 'defaultLanguage', array_merge($langs, array('Generic highlighting' => 'standard'))); ?>

	<!-- Output Style -->
	<?php $sUtil->displaySelect('Output-Style', 'compiler', array('List (with line-numbers, ordered list)' => 'List', 'Inline (without line-numbers, pre-tag)' => 'Inline')); ?>
    
    <!-- Indent -->
    <?php $sUtil->displaySelect('Code-Indent', 'indent', array('Default (use tabs)' => -1, '1 Space' => 1, '2 Spaces' => 2, '3 Spaces' => 3, '4 Spaces' => 4, '5 Spaces' => 5, '6 Spaces' => 6, '7 Spaces' => 7, '8 Spaces' => 8, '9 Spaces' => 9, '10 Spaces' =>10, '11 Spaces' => 11, '12 Spaces' =>12, '13 Spaces' => 13, '14 Spaces' => 14, '15 Spaces' => 15)); ?>
    
    <!-- Mouseover -->
	<?php $sUtil->displaySelect('Mouseover on codelines', 'altLines', array('Enabled' => 'hoverEnabled', 'Disabled' => '')); ?>
	
	<!-- enable langugae shortcodes !-->
	<?php $sUtil->displaySelect('Language Shortcodes', 'languageShortcode', array('Enabled' => 'enabled', 'Disabled' => '')); ?>
	
	<!-- THEME CUSTOMIZER -->
	<?php include('ThemeCustomizer.phtml');?>
	<!-- // THEME CUSTOMIZER -->
	
	<!-- ADVANCED SETTINGS -->
	<h2><?php _e('Advanced'); ?></h2>
	
	<p><strong><?php _e('Warning: These options are for advanced users only!'); ?></strong><br />
	They might be required when using a Content-Delivery-Network (CDN) or another server/location which outsources your CSS+Javascript files. In this case you have to manually include EnlighterJS.js, EnlighterJS.css and the MooTools Framework into your page!
	</p>
    
	<!-- embed css !-->    
    <h3><?php _e('EnlighterJS Styles'); ?></h3>
	<?php $sUtil->displayCheckbox('Include-CSS', 'embedEnlighterCSS') ?>

	<!-- embed JS !-->    
    <h3><?php _e('EnlighterJS Javascript'); ?></h3>
	<?php $sUtil->displayCheckbox('Include-Javascript', 'embedEnlighterJS'); ?>

	<!-- embed MooTools !-->    
    <h3><?php _e('MooTools Javascript Framework'); ?></h3>
	<?php $sUtil->displaySelect('MooTools Source', 'mootoolsSource', array('Your WordPress Site' => 'local', 'Google CDN' => 'google', 'Not include' => 'none')); ?>

    <!-- advanced css selector !-->
    <h3><?php _e('CSS Selector'); ?></h3>
    <p><?php _e('The selector is used to match all generated pre-tags. Normally pre.EnlighterJSRAW should be perfect (all pre-tags generated by the plugin will be highlighted)'); ?></p>
    <p><?php _e('<strong>Default: </strong>pre.EnlighterJSRAW'); ?></p>
    <?php $sUtil->displayInput('CSS Selector', 'selector', 'The CSS selector used to match generated HTML Tags'); ?>
    
    <!-- config type !-->    
    <h3><?php _e('Initialization method'); ?></h3>
	<p><?php _e('EnlighterJS needs to be "initialized" with a special metadata-tag or some startup-codes within a script-tag. Which method should be used ? (metadata based config will not pass the W3C Validator check)'); ?></p>
	<p><?php _e('<strong>Default: </strong>Metadata based config'); ?></p>
	<?php $sUtil->displaySelect('Initialization Method', 'configType', array('Metadata based config' => 'meta', 'Script based config' => 'script')); ?>
	
	<!-- submit !-->
    <?php submit_button(); ?>

</form>

<h2><?php _e('Credits') ?></h2>
<p><a href="http://www.a3non.org/go/enlighterjs">EnlighterJS</a> is developed by <a href="http://andidittrich.de">Andi Dittrich</a>. It's release under the MIT X11 License. Includes: <a href="http://www.eyecon.ro/colorpicker/">Colorpicker</a> by <a href="http://www.eyecon.ro">Stefan Petre</a> - MIT/GPL License</p>
</div>
