<?php
/**
	Descriptionn: Enlighter Admin Settings Page
	Plugin URI: http://www.a3non.org/go/enlighterjs
	Version: 1.2
	Author: Andi Dittrich
	Author URI: http://andidittrich.de
	License: MIT X11-License
	
	Copyright (c) 2013, Andi Dittrich

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
?>
<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="wrap">
<h2><?php _e('Enlighter - Advanced javascript based syntax highlighting', 'enlighter'); ?></h2>

<!-- Breadcrumb -->
<?php add_thickbox(); ?>
<div id='setting-error-settings_updated' class='updated settings-error'> 
<p><strong><?php _e('Enlighter related: ', 'enlighter'); ?></strong>
	<a href="#TB_inline?height=500&width=800&inlineId=EnlighterHelp" class="thickbox" rel="Enlighter Help"><?php _e('View Help', 'enlighter'); ?></a> | 
	<a href="https://github.com/AndiDittrich/WordPress.Enlighter"><?php _e('Enlighter on GitHub', 'enlighter'); ?></a> | 
	<a href="http://wordpress.org/plugins/enlighter/"><?php _e('Enlighter on WordPress.org', 'enlighter'); ?></a> | 
	<a href="https://github.com/AndiDittrich/WordPress.Enlighter/issues"><?php _e('Report a Bug', 'enlighter'); ?></a> |
	<a href="http://static.andidittrich.de/EnlighterJS/Demo.html"><?php _e('Theme Demo', 'enlighter'); ?></a>
</p>
</div>

<!-- Help Overlay Content -->
<?php require('Help.phtml'); ?>

<!-- settings !-->
<form method="post" action="options.php">
    <?php settings_fields('enlighter-settings-group' ); ?>
    
	<!-- appearance !-->
    <h3><?php _e('Appearance'); ?></h3>
    <div class="EnlighterBlockcontent">
	    <p><?php _e('You can specify the default language and theme as well as the some output styles. If you want to customize themes, choose the default theme option "custom"', 'enlighter');?><br />
	    <?php _e('The indent-option will replace each tab at the beginning of a line with a selectable number of space-characters', 'enlighter'); ?></p>
	
	    <!-- Theme -->
		<?php $this->_settingsUtility->displaySelect(__('Default Theme', 'enlighter'), 'defaultTheme', $this->_suppportedThemes); ?>
	    
	    <!-- Language -->
		<?php $this->_settingsUtility->displaySelect(__('Default Language', 'enlighter'), 'defaultLanguage', array_merge($this->_supportedLanguageKeys, array(__('Generic highlighting', 'enlighter') => 'standard'))); ?>
	
		<!-- Output Style -->
		<?php $this->_settingsUtility->displaySelect(__('Output-Style', 'enlighter'), 'compiler', array(__('List (with line-numbers, ordered list)', 'enlighter') => 'List', __('Inline (without line-numbers, pre-tag)', 'enlighter') => 'Inline')); ?>
	    
	    <!-- Indent -->
	    <?php $this->_settingsUtility->displaySelect(__('Code-Indent', 'enlighter'), 'indent', array(__('Default (use tabs)', 'enlighter') => -1, __('1 Space', 'enlighter') => 1, '2 '.__('Spaces', 'enlighter') => 2, '3 '.__('Spaces', 'enlighter') => 3, '4 '.__('Spaces', 'enlighter') => 4, '5 '.__('Spaces', 'enlighter') => 5, '6 '.__('Spaces', 'enlighter') => 6, '7 '.__('Spaces', 'enlighter') => 7, '8 '.__('Spaces', 'enlighter') => 8, '9 '.__('Spaces', 'enlighter') => 9, '10 '.__('Spaces', 'enlighter') =>10, '11 '.__('Spaces', 'enlighter') => 11, '12 '.__('Spaces', 'enlighter') =>12, '13 '.__('Spaces', 'enlighter') => 13, '14 '.__('Spaces', 'enlighter') => 14, '15 '.__('Spaces', 'enlighter') => 15)); ?>
	    
	    <!-- Mouseover -->
		<?php $this->_settingsUtility->displaySelect(__('Mouseover on codelines', 'enlighter'), 'altLines', array(__('Enabled', 'enlighter') => 'hoverEnabled', __('Disabled', 'enlighter') => '')); ?>
		
		<!-- enable langugae shortcodes !-->
		<?php $this->_settingsUtility->displaySelect(__('Language Shortcodes', 'enlighter'), 'languageShortcode', array(__('Enabled', 'enlighter') => 'enabled', __('Disabled', 'enlighter') => '')); ?>
	</div>
	
	<!-- THEME CUSTOMIZER -->
	<?php include('ThemeCustomizer.phtml');?>
	<!-- // THEME CUSTOMIZER -->
	
	<!-- CDN SETTINGS -->
	<h3><?php _e('CDN (Content Delivery Network)', 'enlighter'); ?></h3>
	<div class="EnlighterBlockcontent">		
		<p><?php _e('These options might be required when using a Content-Delivery-Network (CDN) or another server/location which outsources your CSS+Javascript files.', 'enlighter'); ?> <br />
		<?php _e('In this case you have to manually include EnlighterJS.js, EnlighterJS.css and the MooTools Framework into your page!', 'enlighter'); ?><br />
		<?php _e('Custom styles, generated with the ThemeCustomizer are', 'enlighter'); ?> <a href="<?php echo plugins_url('/enlighter/cache/EnlighterJS.custom.css') ?>"><?php _e('available here', 'enlighter'); ?></a> (enlighter/cache/EnlighterJS.custom.css).</p>
		
		<!-- embed css !-->
		<?php $this->_settingsUtility->displayCheckbox(__('Include Enlighter-CSS', 'enlighter'), 'embedEnlighterCSS') ?>
	
		<!-- embed JS !-->
		<?php $this->_settingsUtility->displayCheckbox(__('Include Enlighter-Javascript', 'enlighter'), 'embedEnlighterJS'); ?>
	
		<!-- embed MooTools !-->
		<?php $this->_settingsUtility->displaySelect(__('MooTools Framework Source', 'enlighter'), 'mootoolsSource', array(__('Your WordPress Site', 'enlighter') => 'local', __('Google CDN', 'enlighter') => 'google', __('CDNJS (Cloudfare)', 'enlighter') => 'cdnjs', __('Not include', 'enlighter') => 'none')); ?>
	</div>
	
	<!-- ADVANCED SETTINGS -->
	<h3><?php _e('Advanced Options', 'enlighter'); ?></h3>
	<p><strong><?php _e('Warning: These options are for advanced users only!', 'enlighter'); ?></strong></p>

	<div class="EnlighterBlockcontent">

		<!-- Change wpautop filter priority !-->    
	    <h4><?php _e('"WpAutoP" Filter Priority', 'enlighter'); ?></h4>
	    <p><?php _e('The processing priority of the wpautop filter. Normally the filter will be applied before shortcode is handled and will maybe crash your code-appearance by adding linebreaks and p/br tags.', 'enlighter'); ?><br />
	    <?php _e('The Enlighter-Plugin changes the priority of the filter by default to 12 - this means it will be applied <strong>after</strong> shortcodes are processed by WordPress. <strong>It may can influence other plugins.</strong>', 'enlighter'); ?>
	    </p>
		<?php $this->_settingsUtility->displaySelect(__('Filter-Priority', 'enlighter'), 'wpAutoPFilterPriority', array(__('Default (no changes)', 'enlighter') => 'default', __('Priority 12 (after shortcode)', 'enlighter') => '12')); ?>
		
	    <!-- advanced css selector !-->
	    <h4><?php _e('CSS Selector', 'enlighter'); ?></h4>
	    <p><?php _e('The selector is used to match all generated pre-tags. Normally pre.EnlighterJSRAW should be perfect (all pre-tags generated by the plugin will be highlighted)', 'enlighter'); ?></p>
	    <p><?php _e('<strong>Default: </strong>pre.EnlighterJSRAW', 'enlighter'); ?></p>
	    <?php $this->_settingsUtility->displayInput(__('CSS Selector', 'enlighter'), 'selector', __('The CSS selector used to match generated HTML Tags', 'enlighter')); ?>
	    
	    <!-- config type !-->    
	    <h4><?php _e('Initialization Method', 'enlighter'); ?></h4>
		<p><?php _e('EnlighterJS needs to be "initialized" with a special metadata-tag or some startup-codes within a script-tag. Which method should be used ? (metadata based config will not pass the W3C Validator check)', 'enlighter'); ?></p>
		<p><?php _e('<strong>Default: </strong>Metadata based config', 'enlighter'); ?></p>
		<?php $this->_settingsUtility->displaySelect(__('Initialization Method', 'enlighter'), 'configType', array(__('Metadata based config', 'enlighter') => 'meta', __('Script based config', 'enlighter') => 'script')); ?>
	
		<!-- I18n -->
		<h4><?php _e('I18n (Internationalization)', 'enlighter'); ?></h4>
		<p><?php _e('Should the plugin load language files (if available) to translate the settings page ?', 'enlighter'); ?></p>
		<?php $this->_settingsUtility->displayCheckbox(__('Enable I18n', 'enlighter'), 'enableTranslation'); ?>
	</div>
	
	<!-- submit !-->
    <?php submit_button(); ?>

</form>

<p><a href="http://www.a3non.org/go/enlighterjs">EnlighterJS</a> <?php _e('is developed by', 'enlighter'); ?> <a href="http://andidittrich.de">Andi Dittrich</a>. <?php _e('It`s released under the terms of the MIT X11 License.', 'enlighter'); ?> <?php _e('Includes:', 'enlighter'); ?> <a href="http://www.eyecon.ro/colorpicker/">Colorpicker</a> <?php _e('by', 'enlighter'); ?> <a href="http://www.eyecon.ro">Stefan Petre</a> - MIT/GPL <?php _e('License', 'enlighter'); ?></p>
</div>
