<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="postbox enlighter-postbox">
<h3 class="hndle"><?php _e('System Info', 'enlighter'); ?></h3>
    <div class="inside">
        <!-- Metabox-Content -->
        
        <ul>
            <li><strong>Server</strong></li>
            <?php
            echo '<li>', __('PHP Version:', 'enlighter'), ' <span class="enlighter-text-true">', phpversion(), '</span></li>';
            // json encoding available ?
            if (function_exists('json_encode')) {
                echo '<li>', __('PHP JSON Extension', 'enlighter'), ': <span class="enlighter-text-true">', __('available', 'enlighter'), '</span></li>';
            } else {
                echo '<li>', __('PHP JSON Extension', 'enlighter'), ': <span class="enlighter-text-false">', __('not installed', 'enlighter'), '</span></li>';
            }
            // server os
            echo '<li>', __('Server Software:', 'enlighter'), ' <span class="enlighter-text-true">', PHP_OS, '</span></li>';
            ?>
        </ul>

        <hr />

        <ul>
            <li><strong>Components</strong></li>
            <?php
            // enlighter edition
            echo '<li>', __('Enlighter Plugin:', 'enlighter'), ' <span class="enlighter-text-true">', ENLIGHTER_VERSION, ' CE</span></li>';

            // enlighterjs version
            echo '<li>', __('EnlighterJS Version:', 'enlighter'), ' <span class="enlighter-text-true">', \Enlighter\Versions::getEnlighterJSVersion(), '</span></li>';

            // enlighterjs.tinymce version
            echo '<li>', __('TinyMCE Extension:', 'enlighter'), ' <span class="enlighter-text-true">', \Enlighter\Versions::getTinyMCEPluginVersion(), '</span></li>';

            // enlighterjs.gutenberg version
            echo '<li>', __('Gutenberg Extension:', 'enlighter'), ' <span class="enlighter-text-true">', \Enlighter\Versions::getGutenbergPluginVersion(), '</span></li>';

            // enlighterjs.theme-customizer version
            echo '<li>', __('Theme Customizer:', 'enlighter'), ' <span class="enlighter-text-true">', \Enlighter\Versions::getThemeCustomizerPluginVersion(), '</span></li>';

             // framework version
            echo '<li>', __('WP-Skeleton Version:', 'enlighter'), ' <span class="enlighter-text-true">', ENLIGHTER_WPSKLTN_VERSION, '</span></li>';
            ?>

        </ul>
        
        <hr />
        
        <ul>
            <li><strong>Environment</strong></li>
            <?php
            // plugin cache path writeable ?
            if ($this->_cacheManager->isCacheAccessible()) {
                echo '<li>', __('Cache writeable', 'enlighter'), ': <span class="enlighter-text-true">', __('true', 'enlighter'), '</span></li>';
            } else {
                echo '<li>', __('Cache writeable', 'enlighter'), ': <span class="enlighter-text-false">', __('false', 'enlighter'), '</span></li>';
            }
            // shortcode processor type
            $shortcodeProcessorType = 'NAN';
            if ($shortcodeProcessorType == 'disabled') {
                echo '<li>', __('Shortcode Processor', 'enlighter'), ': <span class="enlighter-text-false">', __('disabled', 'enlighter'), '</span></li>';
            } else if ($shortcodeProcessorType == 'legacy') {
                echo '<li>', __('Shortcode Processor', 'enlighter'), ': <span class="enlighter-text-true">', __('WordPress internal', 'enlighter'), '</span></li>';
            } else {
                echo '<li>', __('Shortcode Processor', 'enlighter'), ': <span class="enlighter-text-true">', __('Enlighter low-level', 'enlighter'), '</span></li>';
            }
            ?>
        </ul>

        <!-- // Metabox-Content -->
    </div>
</div>