<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Webfonts -->
<div class="postbox">
    <h3 class="hndle"><span><?php _e('Webfonts Loader', 'enlighter'); ?></span></h3>

    <div class="inside EnlighterBlockcontent">

        <p><?php _e('Some Enlighter Themes uses modern fonts which may not available for your users by default.'); ?>
            <br/>
            <?php _e('To provide the best visual experience, it`s possible to load the missing fonts automatically using <a href="https://www.google.com/fonts">Google Webfonts</a>.', 'enlighter'); ?>
        </p>

        <!-- Source Code Pro -->
        <h4><?php _e('Fonts', 'enlighter'); ?></h4>
        <?php $this->_settingsUtility->displayCheckbox(__('Source Code Pro', 'enlighter'), 'webfontsSourceCodePro', 'test'); ?>

    </div>
</div>