<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Fonts -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('Fonts', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">


        <h4><?php _e('Compatibility mode', 'enlighter'); ?></h4>
        <?php
                $raw = esc_html($this->_themeCustomizer->loadCustomizerConfig());
        ?>
        <textarea name="enlighter-customizer" style="width: 100%; height: 700px"><?php echo $raw ?></textarea>

    </div>
</div>