<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- BB Press -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('bbPress Forums Plugin', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

        <p><?php _e('These options are related to the popular <a href="https://wordpress.org/plugins/bbpress/" target="_blank">bbPress Forums Plugin</a>.', 'enlighter'); ?><br />
            <?php _e('<strong>Note: </strong> Backtick style code-elements of bbPress will be disabled when enabling one of the extensions to avoid conflicts!', 'enlighter'); ?>
        </p>

        <h4><?php _e('bbPress', 'enlighter'); ?></h4>

        <!-- enable shortcode support !-->
        <?php $this->_settingsUtility->displayCheckbox(
            __('Enlighter shortcodes', 'enlighter'),
            'bbpress-shortcode',
            array(
                'label' => __('Enable', 'enlighter'),
                'description' => __('Enable Shortcode support within bbPress topics and replies. Requires enabled shortcode editing mode!', 'enlighter')
            )
        ); ?>

        <!-- enable markdown support !-->
        <?php $this->_settingsUtility->displayCheckbox(
            __('Markdown fenced codeblocks', 'enlighter'),
            'bbpress-markdown',
            array(
                'label' => __('Enable', 'enlighter'),
                'description' => __('Enable Markdown style fenced code blocks within bbPress topics and replies. Requires enabled markdown editing mode!', 'enlighter')
            )
        ); ?>

    </div>
</div>