<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- jQuery -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('Dynamic Content', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

        <p><?php _e('Support for "load more" buttons. It is required to highlight code sections which are dynamically added to your page via AJAX/XHR!', 'enlighter'); ?></p>

        <p><strong>
        <?php _e('Note: these features are not compatible with Dynamic Resource Invocation (DRI) mode! Disable DRI in case you want to use AJAX based content!', 'enlighter'); ?>
        </strong></p>

        <h4><?php _e('Jetpack', 'enlighter'); ?></h4>

        <!-- enable infninite scroll support !-->
        <?php $this->_settingsUtility->displayCheckbox(
            __('Infinite Scroll', 'enlighter'),
            'ext-infinite-scroll',
            array(
                'label' => __('Enable', 'enlighter'),
                'readmore' => 'https://jetpack.me/support/infinite-scroll/',
                'description' => __('If you use the InfiniteScroll Module, enable this option to load the Enlighter.InfniteScroll extension. It is required to highlight code sections which are dynamically added to your page!', 'enlighter')
            )
        ); ?>

        <h4><?php _e('jQuery AJAX', 'enlighter'); ?></h4>

        <!-- enable ajaxComplete support !-->
        <?php $this->_settingsUtility->displayCheckbox(
            __('Dynamic Ajax Content', 'enlighter'),
            'ext-ajaxcomplete',
            array(
                'label' => __('Enable', 'enlighter'),
                'readmore' => 'https://api.jquery.com/ajaxcomplete/',
                'description' => __('This options adds a trigger to the ajaxComplete event used by jQuery', 'enlighter')
            )
        ); ?>

    </div>
</div>