<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Visual Editor -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('Visual Editor (TinyMCE 4)', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

        <p><?php _e('To use EnlighterJS within Gutenberg you can enable this feature. It loads the EnlighterJS Gutenberg.Plugin.', 'enlighter'); ?><br />
        </p>
        <?php $this->_settingsUtility->displayCheckbox(__('Enable', 'enlighter'), 'gutenbergSupport'); ?>
    </div>
</div>