<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Shortcode Processing -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('Shortcodes', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

        <h4><?php _e('Shortcode Processing', 'enlighter'); ?></h4>
        <p><?php _e('WordPress provides a build-in Shortcode-API to process shortcodes used by third-party plugins. This function may can cause issues when using it in Text-Editor-Mode with unescaped html characters - especially when posting source-code!', 'enlighter'); ?>
            <?php _e('To avoid such issues, Enlighter provides its own, fault tolerant, Shortcode processor (only affects Enlighter shortcodes!).', 'enlighter'); ?><br />
            <?php _e('If you do not need shortcodes (use the Visual-Editor-Integration instead) it is possible to disable the shortcode processing for performance reasons.', 'enlighter'); ?></p>
        <p><?php _e('<strong>Notice</strong>: the LowLevel Shortcode Processor is <strong>not invoked</strong> by the <a href="https://developer.wordpress.org/reference/functions/do_shortcode/">do_shortcode</a> function! If you need shortcode processing in other content section, you should consider to use the legacy version or add custom filters!', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displaySelect(__('Processor', 'enlighter'), 'shortcodeMode', array(__('Enlighter Low-Level (default)', 'enlighter') => 'modern', __('Legacy (WordPress based)', 'enlighter') => 'legacy', __('Disable Shortcodes', 'enlighter') => 'disabled')); ?>

        <div id="EnlighterShortcodeFilters">
        <h4><?php _e('Filter Targets - LowLevel Shortcode Processor', 'enlighter'); ?></h4>
        <p><?php _e('Choose the content-sections to which the shortcode processor should be applied.', 'cryptex'); ?></p>
        <!-- Enable the_content filter -->
        <?php $this->_settingsUtility->displayCheckbox(__('Enable the_content', 'enlighter'), 'shortcodeFilterContent'); ?>

        <!-- Enable the_excerpt filter -->
        <?php $this->_settingsUtility->displayCheckbox(__('Enable the_excerpt', 'enlighter'), 'shortcodeFilterExcerpt'); ?>

        <!-- Enable comment-text filter -->
        <?php $this->_settingsUtility->displayCheckbox(__('Enable comments', 'enlighter'), 'shortcodeFilterComments'); ?>

        <!-- Enable comment-excerpt filter -->
        <?php $this->_settingsUtility->displayCheckbox(__('Enable comments-excerpt', 'enlighter'), 'shortcodeFilterCommentsExcerpt'); ?>

        <!-- Enable Widget-text filter -->
        <?php $this->_settingsUtility->displayCheckbox(__('Enable widget-text', 'enlighter'), 'shortcodeFilterWidgetText'); ?>
        </div>

        <!-- Language Shortcodes -->
        <h4><?php _e('Language Shortcodes', 'enlighter'); ?></h4>
        <p><?php _e('Do you want to use language shortcodes like [js] ? Disable it when your using other plugins which uses such shortcodes!', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displayCheckbox(__('Enable Language Shortcodes', 'enlighter'), 'languageShortcode'); ?>

        <!-- Inline Highlighting -->
        <h4><?php _e('Inline Syntax Highlighting', 'enlighter'); ?></h4>
        <p><?php _e('Should shortcodes without linebreaks insinde handled as inline-code ?', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displayCheckbox(__('Enable Inline Syntax Highlighting', 'enlighter'), 'enableInlineHighlighting'); ?>


     </div>
</div>