<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Text Editor -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('QuickTags', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">
        
        <!-- Quicktags -->
        <h4><?php _e('Integration', 'enlighter'); ?></h4>
        <p><?php _e('QuickTags are used to simplify the editing process when working in text/html mode. A bunch of QuickTags (all registered languages) can be added to the Text/HTML Editor Toolbar.', 'enlighter'); ?></p>

        <?php $this->_settingsUtility->displayCheckbox(
            __('Backend Integration', 'enlighter'),
            'quicktag-backend',
            array(
                'label' => __('Enable', 'enlighter'),
                'description' => __('Use QuickTags within the legacy text/html editor?', 'enlighter')
            )
        ); ?>

        <?php $this->_settingsUtility->displayCheckbox(
            __('Frontend Integration', 'enlighter'),
            'quicktag-frontend',
            array(
                'label' => __('Enable', 'enlighter'),
                'description' => __('Do you want to use the QuickTags extensions in your frontend (website)?', 'enlighter')
            )
        ); ?>

        <h4><?php _e('Settings', 'enlighter'); ?></h4>
        <p><?php _e('HTML Tags are fully compatible with TinyMCE.', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displaySelect(
            __('QuickTag Mode', 'enlighter'),
            'quicktag-mode',
            array(
                'html' => __('Print HTML code', 'enlighter'),
                'shortcode' => __('Print language shortcodes', 'enlighter'),
                'legacy_shortcode' => __('Print legacy Enlighter shortcodes', 'enlighter')
            ),
            array(
                'description' => __('QuickTags can generate shortcode or direct html code.', 'enlighter')
            )
            ); ?>
    </div>
</div>


