<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Text Editor -->
<div class="postbox">
    <h3 class="hndle"><span><?php _e('Text/HTML Editor', 'enlighter'); ?></span></h3>
    <div class="inside EnlighterBlockcontent">
        <!-- Quicktags -->
        <h4><?php _e('QuickTags', 'enlighter'); ?></h4>
        <p><?php _e('QuickTags are used to simplify the editing process when working in text/html mode. A bunch of QuickTags (all registered languages) can be added to the Text/HTML Editor Toolbar.', 'enlighter'); ?></p>


        <?php $this->_settingsUtility->displayCheckbox(__('Enable Backend Integration', 'enlighter'), 'enableQuicktagBackendIntegration'); ?>

        <p><?php _e('Do you want to use the QuickTags extensions in your frontend (website)?', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displayCheckbox(__('Enable Frontend Integration', 'enlighter'), 'enableQuicktagFrontendIntegration'); ?>

        <p><?php _e('HTML Tags are fully compatible with the Visual Editor Mode.', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displaySelect(__('QuickTag Mode', 'enlighter'), 'editorQuicktagMode', array(__('Print HTML Tags (default)', 'enlighter') => 'html', __('Print Shortcode Tags', 'enlighter') => 'shortcode', __('Disable QuickTags', 'enlighter') => 'disabled')); ?>
    </div>
</div>


