<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Visual Editor -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('Visual Editor (TinyMCE 4)', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

        <!-- TinyMCE Integration -->
        <h4><?php _e('Visual Editor Integration', 'enlighter'); ?></h4>
        <?php $this->_settingsUtility->displayCheckbox(
            __('Backend Integration', 'enlighter'), 
            'tinymce-backend',
            array(
                'label' => 'Enable',
                'description' => __('Use EnlighterJS within TinyMCE.', 'enlighter')
            ));
        ?>
        <?php $this->_settingsUtility->displayCheckbox(
            __('Frontend Integration', 'enlighter'),
            'tinymce-frontend',
            array(
                'label' => 'Enable',
                'readmore' => 'https://github.com/EnlighterJS/Plugin.WordPress/tree/master/docs/TinyMCE.md',
                'description' => __('Do you want to use the Visual Editor extensions in your frontend (website) ?', 'enlighter')
            ));
        ?>

        <!-- Editor Settings -->
        <h4><?php _e('Editor formats', 'enlighter'); ?></h4>
        <?php $this->_settingsUtility->displayCheckbox(
            __('Add editor formats', 'enlighter'),
            'tinymce-formats',
            array(
                'label' => 'Enable',
                'description' => __('In addition to the code-insert button, Enlighter can add a set formats to the editor.', 'enlighter')
            ));
        ?>

        <h4><?php _e('Tab indentation', 'enlighter'); ?></h4>
        <p><?php _e('This option disables the <strong>tabfocus plugin</strong> and requires that the Enlighter <code>indent</code> option has been set to spaces!', 'enlighter'); ?></p>
        <?php $this->_settingsUtility->displayCheckbox(
            __('Tab Indentation', 'enlighter'),
            'tinymce-tabindentation',
            array(
                'label' => 'Enable',
                'description' => __('By default, the <kbd>tab</kbd> button does not add indentation to the content. Enlighter comes with its own editing plugin which allows you to use tabs within the Editor to align code.', 'enlighter')
            ));
            ?>

        <h4><?php _e('Shortcuts', 'enlighter'); ?></h4>
        <?php $this->_settingsUtility->displayCheckbox(
            __('Keyboard shortcut', 'enlighter'),
            'tinymce-keyboardshortcuts',
            array(
                'label' => 'Enable',
                'description' => __('The default keyboard shortcut (shift+alt+x) action can be modified to convert the current selection into an Enlighter codeblock.', 'enlighter')
            ));
        ?>

        <!-- TinyMCE Tweaks -->
        <h4><?php _e('Tweaks', 'enlighter'); ?></h4>
        <?php $this->_settingsUtility->displayCheckbox(
            __('Automatic width (max)', 'enlighter'),
            'tinymce-autowidth',
            array(
                'label' => 'Enable',
                'description' => __('WordPress Limits the Editor-Width to ~600px. You can disable this limit - might be useful for posting source-code!', 'enlighter')
            ));
        ?>

    </div>
</div>

<!-- Visual Editor -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('Editor Pane Appearance', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

    <p><?php _e('It is also possible to influence the code-block styles of the Visual-Editor. Maybe you prefer another background color or font-family.', 'enlighter'); ?></p>

    <?php
        // font family
        $this->_settingsUtility->displaySelect(
            __('Font family', 'enlighter'),
            'tinymce-font',
            $this->_fontManager->getFonts(),
            array(
                'description' => __('Select the font class of the editor area. Note: the fonts have to available on your pc/device!', 'enlighter')
            )
        );

        // font size
        $this->_settingsUtility->displayInput(
            __('Font size', 'enlighter'), 
            'tinymce-fontsize', 
            array(
                'label' => __('e.g. 0.7em', 'enlighter')
            )
        );

        // line height
        $this->_settingsUtility->displayInput(
            __('Line height', 'enlighter'), 
            'tinymce-lineheight',
            array(
                'label' => __('e.g. 1.4em', 'enlighter')
            )
        );

        // font color
        $this->_settingsUtility->displayInput(
            __('Font color', 'enlighter'), 
            'tinymce-color', 
            array(
                'cssClass' => 'enlighter-colorpicker',
                'description' => __('Text color of the editor area', 'enlighter'),
                'label' => __('e.g. #565b60', 'enlighter')
            )
        );
        
        // background color
        $this->_settingsUtility->displayInput(
            __('Background color', 'enlighter'), 
            'tinymce-bgcolor', 
            array(
                'cssClass' => 'enlighter-colorpicker',
                'description' => __('Background color of the editor area (Enlighter sourcecode section)', 'enlighter'),
                'label' => __('e.g. #f7f7f7', 'enlighter')
            )
        );
    ?>

</div>
</div>
