<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="headline">
    <h3 class="headline-title">Here we are! Enlighter 4 and EnlighterJS 3</h3>

    <p class="introduction"></p>

    <p>Everything has changed. <strong>This release is not backward compatible!</strong><br />
    Custom themes and custom changes cannot be converted.</p>
    
    <p style="color:#68a800"><strong>Codeblocks within post/pages/comments are fully compatible - everything will work as expected.</strong></p>
</div>

<hr />

<div class="column-layout-2">

    <div class="col-md-2">
        <div class="news-section">
            <h4>New languages</h4>

            <div class="news-image">
                <img
                    src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/golang.png'); ?>"
                    alt="golang example">
            </div>

            <p>GO, RUST, Scala, YAML, VHDL, Kotlin, TypeScript, Groovy, LESS, SASS, SCSS, Dockerfile, Powershell, VB, Swift, QML, Prolog, ABAP, Verilog, Purebasic. <br />
            <strong>ALL language support file have been re-created from scratch!</strong></p>

        </div>

    </div>

    <div class="col-md-2">
        <div class="news-section">
            <h4>New themes</h4>

            <div class="news-image">
                <img
                    src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/bootstrap4.png'); ?>"
                    alt="bootstrap4">
            </div>

            <p>Dracula, Monokai and Bootstrap4 are added. <br />
            <strong>ALL themes have been re-created from scratch!</strong></p>

        </div>

    </div>

    <div class="clear"></div>

</div>
