<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="headline">
    <h3 class="headline-title">Enlighter v4 + EnlighterJS v3</h3>

    <div class="featured-image">
    </div>

    <p class="introduction">Here we are!</p>

    <p>xxx</p>

</div>

<hr />

<div class="column-layout-2">

    <div class="col-md-2">
        <div class="news-section">
            <h4>Compatibility Mode</h4>

            <div class="news-image">
                <img
                    src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/bbpress_markdown.png'); ?>"
                    alt="Use Enlighter with JetPack Markdown.">
            </div>

            <p>xxx</p>

        </div>

    </div>

    <div class="col-md-2">
        <div class="news-section">
            <h4>Environment Checks</h4>

            <div class="news-image">
                <img
                    src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/environment_check.png'); ?>"
                    alt="Environment Check">
            </div>

            <p>xxx</p>

        </div>

    </div>

    <div class="clear"></div>

</div>
