<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<div class="headline">
    <h3 class="headline-title">Gutenberg Left-Align-Indentation</h3>

    <p class="introduction">
        Align content to the left and remove leading whitespaces.
    </p>

    <div class="news-image">
        <img
            src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/gutenberg-leftalign.gif'); ?>"
            alt="Gutenberg Left-Align-Indentation">
    </div>

</div>

<hr />

<div class="column-layout-2">

    <div class="col-md-2">
        <div class="news-section">
            <h4>Dart language Support</h4>

            <div class="news-image">
                <img
                    src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/dart.png'); ?>"
                    alt="dart example">
            </div>

            <p>EnlighterJS 3.5 with Dart language support</p>

        </div>

    </div>

    <div class="col-md-2">
        <div class="news-section">
            <h4>Dynamic-Resource-Invocation Re-Implemented</h4>

            <div class="news-image">
                <img
                    src="<?php echo \Enlighter\skltn\ResourceManager::getResourceUrl('about/bootstrap4.png'); ?>"
                    alt="bootstrap4">
            </div>

            <p>DRI compatibility for bbpress and dynamic content (jquery load, jetpack infinity scroll). <br />
            <strong>Javascript based dynamic-resource-invocation to load the EnlighterJS assets dynamically when needed (client side)</strong></p>

        </div>

    </div>

    <div class="clear"></div>

</div>
