<p>You can use your own <a href="https://enlighterjs.org">EnlighterJS</a> Themes by uploading them into a directory named <code>enlighter/</code> within your theme (you have to create it by your own).<br />
The full documentation about external themes is <a href="https://github.com/EnlighterJS/documentation/blob/master/wordpress/ExternalThemes.md">available here.</a></p>

<p>Please pay attention to the different theme types:</p>

<hr />
<p><strong>Type 1: Public/Payed WordPress Themes</strong></p>
<p><ul><li><em>Themes like WordPress buildin `twentytwelve` or `twentyten`.</em></li>
<li><strong>Attention:</strong> It is strongly recommened to create a <a href="https://codex.wordpress.org/Child_Themes">Child Theme</a> to protect the created <code>enlighter/</code> directory from being erased during the update-process!</li>
</ul></p>

<hr />

<p><strong>Type 2: Custom/Selfmade WordPress Themes</strong></p>
<p><ul>
<li><em>Custom themes are created by your own and you manage the update-process by yourself. There is no danger by adding additional directories to your theme!</em></li>
</ul></p>
