<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Enlighter JS Resources !-->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('EXPERIMENTAL OPTIONS', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

    <p class="enlighter-text-false">
        <?php _e('Warning: These options are for advanced users only and subjected to change!', 'enlighter'); ?>
    </p>

    </div>
</div>