<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- Legacy Code Processing -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('Compatibility Mode / 3rd Party Migration', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

        <h4><?php _e('Compatibility', 'enlighter'); ?></h4>
        <p>
        <?php _e('Do you use plugins which did not support Enlighter directly? In this case the compatibility mode converts the legacy code (desgined for other syntax highlighting plugins) into Enlighter codeblocks on the fly.', 'enlighter'); ?><br />
        <?php _e('This feature allows you to migrate to Enlighter without altering your old posts.', 'enlighter'); ?>
        </p>

    </div>
</div>