<?php if (!defined('ENLIGHTER_INIT')) die('DIRECT ACCESS PROHIBITED'); ?>

<!-- jQuery -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('Dynamic Content', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

        <p><?php _e('Support for "load more" buttons. It is required to highlight code sections which are dynamically added to your page via AJAX/XHR!', 'enlighter'); ?></p>

        <p><strong>
        <?php _e('Note: these features are not compatible with Dynamic Resource Invocation (DRI) mode! Disable DRI in case you want to use AJAX based content!', 'enlighter'); ?>
        </strong></p>

        <h4><?php _e('Jetpack', 'enlighter'); ?></h4>

        <!-- enable infninite scroll support !-->
        <?php $this->_settingsUtility->displayCheckbox(
            __('Infinite Scroll', 'enlighter'),
            'ext-infinite-scroll',
            array(
                'label' => __('Enable', 'enlighter'),
                'readmore' => 'https://jetpack.me/support/infinite-scroll/',
                'description' => __('If you use the InfiniteScroll Module, enable this option to load the Enlighter.InfniteScroll extension. It is required to highlight code sections which are dynamically added to your page!', 'enlighter')
            )
        ); ?>

        <h4><?php _e('jQuery AJAX', 'enlighter'); ?></h4>

        <!-- enable ajaxComplete support !-->
        <?php $this->_settingsUtility->displayCheckbox(
            __('Dynamic Ajax Content', 'enlighter'),
            'ext-ajaxcomplete',
            array(
                'label' => __('Enable', 'enlighter'),
                'readmore' => 'https://api.jquery.com/ajaxcomplete/',
                'description' => __('This options adds a trigger to the ajaxComplete event used by jQuery', 'enlighter')
            )
        ); ?>

    </div>
</div>


<!-- BB Press -->
<div class="postbox enlighter-postbox">
    <h3 class="hndle"><span><?php _e('bbPress Forums Plugin', 'enlighter'); ?></span></h3>
    <div class="inside enlighter-setting-section">

        <p><?php _e('These options are related to the popular <a href="https://wordpress.org/plugins/bbpress/" target="_blank">bbPress Forums Plugin</a>.', 'enlighter'); ?><br />
            <?php _e('<strong>Note: </strong> Backtick style code-elements of bbPress will be disabled when enabling one of the extensions to avoid conflicts!', 'enlighter'); ?>
        </p>

        <h4><?php _e('bbPress', 'enlighter'); ?></h4>

        <!-- enable shortcode support !-->
        <?php $this->_settingsUtility->displayCheckbox(
            __('Enlighter shortcodes', 'enlighter'),
            'bbpress-shortcode',
            array(
                'label' => __('Enable', 'enlighter'),
                'description' => __('Enable Shortcode support within bbPress topics and replies. Requires enabled shortcode editing mode!', 'enlighter')
            )
        ); ?>

        <!-- enable markdown support !-->
        <?php $this->_settingsUtility->displayCheckbox(
            __('Markdown fenced codeblocks', 'enlighter'),
            'bbpress-markdown',
            array(
                'label' => __('Enable', 'enlighter'),
                'description' => __('Enable Markdown style fenced code blocks within bbPress topics and replies. Requires enabled markdown editing mode!', 'enlighter')
            )
        ); ?>

    </div>
</div>